import './globals.css';
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Theme, ThemePanel } from '@radix-ui/themes';
import { Toaster } from 'sonner';

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'CodeAtlas',
    description: 'Generated by Next.js with the App Router and Tailwind CSS',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <Theme accentColor="blue" grayColor="sand" radius="large" scaling="95%">
                    {children}
                    <ThemePanel defaultOpen={false} />
                </Theme>
                <Toaster richColors position="top-center" />
            </body>
        </html>
    );
}
